DROP TABLE clientes CASCADE CONSTRAINTS;

DROP TABLE DETALLE_COMPRA CASCADE CONSTRAINTS;
DROP TABLE DETALLE_VENTA CASCADE CONSTRAINTS;
DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE COMPRAS CASCADE CONSTRAINTS;
DROP TABLE VENTAS CASCADE CONSTRAINTS;
DROP TABLE FACTURA CASCADE CONSTRAINTS;

-------------------------------------------
CREATE TABLE clientes (
    id_cliente       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(50) NOT NULL,
    primer_apellido  VARCHAR2(50) NOT NULL,
    segundo_apellido VARCHAR2(50),
    telefono         VARCHAR2(20),
    email            VARCHAR2(100),
    direccion        VARCHAR2(150)
);

CREATE TABLE empleados (
    id_empleado       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR2(50) NOT NULL,
    primer_apellido   VARCHAR2(50) NOT NULL,
    segundo_apellido  VARCHAR2(50),
    salario           NUMBER(10, 2),
    cargo             VARCHAR2(50)
);


CREATE TABLE inventario (
    id_inventario      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_producto        NUMBER NOT NULL,
    cantidad           NUMBER(10) NOT NULL,
    fecha_vencimiento  DATE,
    precio             NUMBER(10, 2),
    estado             VARCHAR2(30),

    CONSTRAINT fk_inventario_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto)
);

CREATE TABLE ingredientes (
    id_ingrediente  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(100) NOT NULL,
    cantidad        NUMBER(10, 2),
    id_receta       NUMBER
);

ALTER TABLE ingredientes
ADD CONSTRAINT fk_ingrediente_receta
FOREIGN KEY (id_receta)
REFERENCES recetas(id_receta);

CREATE TABLE recetas (
    id_receta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR2(100) NOT NULL
);

CREATE TABLE productos (
    id_producto   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(100) NOT NULL,
    tipo          VARCHAR2(50),
    precio        NUMBER(10, 2),
    descripcion   VARCHAR2(200),
    id_receta     NUMBER,

    CONSTRAINT fk_producto_receta
        FOREIGN KEY (id_receta)
        REFERENCES recetas(id_receta)
);


CREATE TABLE compras (
    id_compra              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_ingrediente         NUMBER NOT NULL,
    fecha                  DATE DEFAULT SYSDATE,
    cantidad_ingredientes  NUMBER(10, 2),
    monto_total            NUMBER(10, 2),

    CONSTRAINT fk_compras_ingrediente
        FOREIGN KEY (id_ingrediente)
        REFERENCES ingredientes(id_ingrediente)
);

CREATE TABLE ventas (
    id_ventas                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_cliente                 NUMBER NOT NULL,
    monto_total                NUMBER(10, 2),
    cantidad_productos_total  NUMBER(10),
    id_empleado                NUMBER NOT NULL,
    id_producto                NUMBER NOT NULL,

    -- Claves foráneas
    CONSTRAINT fk_ventas_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES clientes(id_cliente),

    CONSTRAINT fk_ventas_empleado
        FOREIGN KEY (id_empleado)
        REFERENCES empleados(id_empleado),

    CONSTRAINT fk_ventas_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto)
);

CREATE TABLE FACTURA (
    ID_FACTURA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_VENTAS NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    IMPUESTO NUMBER(10, 2) NOT NULL,
    SUBTOTAL NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_FACTURA_VENTAS FOREIGN KEY (ID_VENTAS)
        REFERENCES VENTAS(ID_VENTAS)
);


