CREATE TABLE auditoria_clientes (
    id_auditoria   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_cliente     NUMBER,
    accion         VARCHAR2(20),
    usuario        VARCHAR2(30),
    fecha_accion   DATE,
    datos_antiguos VARCHAR2(500)
);

CREATE OR REPLACE TRIGGER trg_auditoria_clientes_insert
AFTER INSERT OR UPDATE OR DELETE ON clientes
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO auditoria_clientes (id_cliente, accion, usuario, fecha_accion)
        VALUES (:NEW.id_cliente, 'INSERT', USER, SYSDATE);
  END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_auditoria_clientes_update
AFTER INSERT OR UPDATE OR DELETE ON clientes
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO auditoria_clientes (id_cliente, accion, usuario, fecha_accion, datos_antiguos)
        VALUES (:OLD.id_cliente, 'UPDATE', USER, SYSDATE,
                'Nombre anterior: ' || :OLD.nombre || ', Teléfono anterior: ' || :OLD.telefono);
  END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_auditoria_clientes_delete
AFTER INSERT OR UPDATE OR DELETE ON clientes
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO auditoria_clientes (id_cliente, accion, usuario, fecha_accion, datos_antiguos)
        VALUES (:OLD.id_cliente, 'DELETE', USER, SYSDATE,
                'Nombre: ' || :OLD.nombre || ', Teléfono: ' || :OLD.telefono);
    END IF;
END;
/


